### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [alwinruby/Netflix-Stocks-Capstone#1]
Overall, great job! Your code was very clean and easy to read, and it looked like you knew exactly what to do and how to do it. I also really like the appearance of your slides, I thought they were really nicely designed.

**Comment by alwinruby** [comment]
Thank you very much.  Would it have been good to add a script to my presentation?

**Comment by Aerodlyn** [comment]
Do you mean like what you would say if you were going to be giving the presentation? If so, I think that isn't necessary.

**Comment by alwinruby** [comment]
OK Thank You
